apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: assignment-ingress
  namespace: assignment

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

spec:
  ingressClassName: alb

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: assignment-service

                port:
                  number: 80