name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      AWS_REGION: ap-south-1
      EKS_CLUSTER_NAME: assignment-eks
      ECR_REPOSITORY: flask-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/flask-app:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/flask-app:latest

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ap-south-1 \
            --name assignment-eks

      - name: Update Deployment
        run: |
          kubectl set image deployment/assignment-app \
          flask-app=${{ steps.login-ecr.outputs.registry }}/flask-app:${{ github.sha }} \
          -n assignment

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/assignment-app -n assignment